"""initial schema

Revision ID: b7915fbf1e3a
Revises: 995165126614
Create Date: 2026-07-21 12:57:57.984922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7915fbf1e3a'
down_revision: Union[str, None] = '995165126614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###